import type { Metadata } from 'next'

import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import CallToAction from '@/components/CallToAction';


export const metadata: Metadata = {
  title: "L'Èquipe",
  description: 'The Generated by create next app',
}

export default function RootLayout({children,}:{children: React.ReactNode}) {
  return (
    <html lang="de">
      <body className='bg-blue-10'>
        <header>
          <Navbar />
        </header>

        <main className='relative overflow-hidden z-20 bg-white bottom-[100px]'>
          {children}
        </main>

        <CallToAction/>
        
        <Footer />
      </body>
    </html>
  )
}
